project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links: repo

format:
  html:
    comments:
      hypothesis: false
    toc: true
    toc-depth: 5
    html-math-method: katex
  pdf:
    documentclass: article
    header-includes:
        - \usepackage{mathtools}
        - \newcommand{\GPTpath}{GPT^{\text{path}}}
        - \newcommand{\R}{\mathbb{R}}


execute:
  freeze: true


