project:
  type: website
  output-dir: public
  render:
    - index.qmd

website:
  title: "G4H - From embeddings to causal inference"
  site-url: https://meilame-tayebjee.github.io/G4H-Report/
  repo-url: https://github.com/meilame-tayebjee/G4H-Report
  repo-actions: [
    "source",
    "issue",
    "edit",
  ]
  repo-branch: main

format:
  html:
    theme: litera
    comments:
      hypothesis: false
    toc: true
    toc-depth: 5
    html-math-method: katex
  pdf:
    documentclass: scrartcl
    header-includes:
        - \usepackage{mathtools}
        - \newcommand{\GPTpath}{GPT^{\text{path}}}
        - \newcommand{\R}{\mathbb{R}}
    output-file: G4H-report.pdf

execute:
  freeze: true


