project:
  type: website
  render:
    - mydocs/*/*.qmd
    - index.qmd
    - cards/*.qmd

website:
  page-navigation: true
  title: "G4H - From embeddings to causal inference"
  site-url: https://meilame-tayebjee.github.io/G4H-Report/
  repo-url: https://github.com/meilame-tayebjee/G4H-Report
  repo-actions: [
    "source",
    "issue",
    "edit",
  ]
  repo-branch: main
  navbar:
    right:
      - icon: github
        href: "https://github.com/meilame-tayebjee/G4H-Report"
        aria-label: GitHub

execute:
  freeze: true
