project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links: repo

format:
  html:
    comments:
      hypothesis: true
  pdf:
    documentclass: article
    header-includes:
        - \usepackage{mathtools}


execute:
  freeze: true


